[package]
name = "motolii-native-renderer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
egui = "0.35.0"
egui-wgpu = "0.35.0"
lyon_path = "1.0.19"
lyon_tessellation = "1.0.19"
motolii-doc = { path = "../../../crates/motolii-doc" }
pollster = "0.4"
re_log_types = { git = "https://github.com/oshikaidesu/rerun", rev = "0b2be857bea452f3b7a9d9c7d74d9250bb7e9949" }
re_chunk = { git = "https://github.com/oshikaidesu/rerun", rev = "0b2be857bea452f3b7a9d9c7d74d9250bb7e9949" }
re_renderer = { git = "https://github.com/oshikaidesu/rerun", rev = "0b2be857bea452f3b7a9d9c7d74d9250bb7e9949", default-features = false }
re_sdk_types = { git = "https://github.com/oshikaidesu/rerun", rev = "0b2be857bea452f3b7a9d9c7d74d9250bb7e9949" }
re_view_spatial = { git = "https://github.com/oshikaidesu/rerun", rev = "0b2be857bea452f3b7a9d9c7d74d9250bb7e9949", default-features = false }
wgpu = "29"

[target.'cfg(target_os = "macos")'.dependencies]
skia-safe = { version = "0.99.0", default-features = false, features = ["binary-cache"] }

[target.'cfg(target_os = "windows")'.dependencies]
skia-safe = "0.99.0"

[workspace]
