require 'pathname'

workspace_dir = Pathname.new(__dir__)
workspace_dir = workspace_dir.parent until
  File.exist?("#{workspace_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") ||
  workspace_dir.expand_path.to_s == '/'
require "#{workspace_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"

prepare_react_native_project!

target 'MotoliiRnLegacy-macOS' do
  platform :macos, '14.0'
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
