use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde_json::Value;

const FIXTURE: &str = "fixtures/browser-panel.json";

fn main() {
    println!("cargo:rerun-if-changed={FIXTURE}");
    let source = fs::read_to_string(FIXTURE).expect("read Browser panel fixture");
    let root: Value = serde_json::from_str(&source).expect("parse Browser panel fixture");
    let generated = generate(&root).expect("validate Browser panel fixture");
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("browser_panel_fixture.rs");
    fs::write(output, generated).expect("write generated Browser panel fixture");
}

fn generate(root: &Value) -> Result<String, String> {
    reject_unknown_keys(root, &["version", "surfaces"], "root")?;
    if root.get("version").and_then(Value::as_u64) != Some(1) {
        return Err("version must be 1".into());
    }
    let surfaces = array(root, "surfaces")?;
    if surfaces.is_empty() {
        return Err("surfaces must not be empty".into());
    }

    let mut surface_ids = BTreeSet::new();
    let mut card_ids = BTreeSet::new();
    let mut output = String::from("// @generated by crates/motolii-ui/build.rs; do not edit.\n");
    output.push_str("const GENERATED_SURFACES: &[BrowserPanelSpec] = &[\n");

    for surface in surfaces {
        reject_unknown_keys(surface, &["id", "label", "sources", "cards"], "surface")?;
        let id = text(surface, "id")?;
        if !surface_ids.insert(id) {
            return Err(format!("duplicate surface id: {id}"));
        }
        let label = text(surface, "label")?;
        let sources = array(surface, "sources")?;
        let cards = array(surface, "cards")?;
        if sources.is_empty() || cards.is_empty() {
            return Err(format!("surface {id} must have sources and cards"));
        }

        output.push_str("BrowserPanelSpec { ");
        output.push_str(&format!("id: {id:?}, label: {label:?}, sources: &["));
        for source in sources {
            let source = source
                .as_str()
                .ok_or_else(|| format!("surface {id} has a non-string source"))?;
            output.push_str(&format!("{source:?},"));
        }
        output.push_str("], cards: &[\n");
        for card in cards {
            reject_unknown_keys(card, &["id", "glyph", "name", "kind"], "card")?;
            let card_id = text(card, "id")?;
            if !card_ids.insert(card_id) {
                return Err(format!("duplicate card id: {card_id}"));
            }
            output.push_str("BrowserCardSpec { ");
            for key in ["id", "glyph", "name", "kind"] {
                output.push_str(&format!("{key}: {:?}, ", text(card, key)?));
            }
            output.push_str("},\n");
        }
        output.push_str("] },\n");
    }
    output.push_str("];\n");
    Ok(output)
}

fn array<'a>(value: &'a Value, key: &str) -> Result<&'a [Value], String> {
    value
        .get(key)
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .ok_or_else(|| format!("{key} must be an array"))
}

fn text<'a>(value: &'a Value, key: &str) -> Result<&'a str, String> {
    let text = value
        .get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("{key} must be a string"))?;
    if text.trim().is_empty() {
        return Err(format!("{key} must not be empty"));
    }
    Ok(text)
}

fn reject_unknown_keys(value: &Value, allowed: &[&str], context: &str) -> Result<(), String> {
    let object = value
        .as_object()
        .ok_or_else(|| format!("{context} must be an object"))?;
    if let Some(key) = object.keys().find(|key| !allowed.contains(&key.as_str())) {
        return Err(format!("unknown {context} field: {key}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    fn rejects_unknown_version() {
        let fixture = serde_json::json!({"version": 2, "surfaces": []});
        assert_eq!(generate(&fixture), Err("version must be 1".into()));
    }

    #[test]
    fn rejects_duplicate_ids() {
        let fixture = serde_json::json!({
            "version": 1,
            "surfaces": [{
                "id": "one",
                "label": "One",
                "sources": ["All"],
                "cards": [
                    {"id": "same", "glyph": "A", "name": "A", "kind": "Item"},
                    {"id": "same", "glyph": "B", "name": "B", "kind": "Item"}
                ]
            }]
        });
        assert_eq!(generate(&fixture), Err("duplicate card id: same".into()));
    }

    #[test]
    fn rejects_css_like_escape_hatches() {
        let fixture = serde_json::json!({
            "version": 1,
            "surfaces": [{
                "id": "one",
                "label": "One",
                "style": {"background": "#000"},
                "sources": ["All"],
                "cards": [{"id": "a", "glyph": "A", "name": "A", "kind": "Item"}]
            }]
        });
        assert_eq!(
            generate(&fixture),
            Err("unknown surface field: style".into())
        );
    }
}
