//! M2E-10: nested scaffold コンパイル専用 cfg + OUT_DIR 生成。
//!
//! Cargo feature にしない(`--all-features` / クリーン checkout 安全)。
//! `#[path]` をソースに置かない(rustfmt が cfg を無視して欠落ファイルで落ちるため)。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=MOTOLII_SCAFFOLD_FIXTURE");
    println!("cargo:rustc-check-cfg=cfg(motolii_scaffold_fixture)");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("scaffold_fixture_mods.rs");

    if env::var_os("MOTOLII_SCAFFOLD_FIXTURE").is_none() {
        fs::write(&dest, "// M2E-10: scaffold fixture inactive\n").expect("write inactive stub");
        return;
    }

    println!("cargo:rustc-cfg=motolii_scaffold_fixture");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let gen_dir = manifest.join("../../target/scaffold-plugin-fixture/in_plugin");
    let gen_dir = gen_dir.canonicalize().unwrap_or(gen_dir);
    println!(
        "cargo:rerun-if-changed={}",
        gen_dir.join("mod.rs").display()
    );

    let body = emit_path_mods(&gen_dir);
    fs::write(&dest, body).expect("write scaffold_fixture_mods.rs");
}

fn emit_path_mods(gen_dir: &Path) -> String {
    let mut body = String::from("// M2E-10: generated by build.rs from scaffold fixture\n");
    let Ok(entries) = fs::read_dir(gen_dir) else {
        body.push_str("// fixture dir missing\n");
        return body;
    };
    let mut mods: Vec<(String, PathBuf)> = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem == "mod" {
            continue;
        }
        mods.push((stem.to_string(), path));
    }
    mods.sort_by(|a, b| a.0.cmp(&b.0));
    for (name, path) in mods {
        let abs = path
            .canonicalize()
            .unwrap_or(path)
            .display()
            .to_string()
            .replace('\\', "/");
        body.push_str(&format!("#[path = \"{abs}\"]\npub mod {name};\n"));
        println!("cargo:rerun-if-changed={abs}");
    }
    body
}
