import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  shell: {flex: 1, minWidth: 980, minHeight: 650, backgroundColor: '#111315'},
  chromeModalScrim: {position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.45)', alignItems: 'center', justifyContent: 'center', zIndex: 20},
  chromeModalCard: {width: 420, maxWidth: '90%', backgroundColor: '#1b1d20', borderWidth: 1, borderColor: '#3a3d41'},
  chromeModalHeader: {height: 31, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 9, borderBottomWidth: 1, borderBottomColor: '#3a3d41'},
  chromeModalActions: {flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 8, paddingVertical: 10},
  chromeModalStatus: {paddingHorizontal: 10, paddingBottom: 10, fontSize: 9, color: '#858a8d'},
  titlebar: {height: 34, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#36393d', backgroundColor: '#202224'},
  brand: {fontSize: 12, fontWeight: '800', letterSpacing: 1.4, color: '#f2f2f0'},
  project: {marginLeft: 14, fontSize: 11, color: '#d5d6d3'},
  buildLabel: {marginLeft: 14, fontSize: 8, color: '#858a8d'},
  grow: {flex: 1},
  titleAction: {fontSize: 10, color: '#d8d8d5', paddingVertical: 6, paddingHorizontal: 10, marginLeft: 6, borderWidth: 1, borderColor: '#414448'},
  titleActionDisabled: {opacity: 0.4},
  titleActionText: {fontSize: 10, color: '#d8d8d5'},
  commandbar: {height: 32, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: '#36393d', backgroundColor: '#151719'},
  commandToolButton: {width: 32, height: 24, alignItems: 'center', justifyContent: 'center'},
  commandTool: {width: 32, textAlign: 'center', fontSize: 12, color: '#b7b9bb'},
  commandToolActive: {borderWidth: 1, borderColor: '#d7d8d5'},
  breadcrumb: {marginLeft: 14, fontSize: 10, color: '#999d9f'},
  breadcrumbStrong: {fontWeight: '700', color: '#e7e7e4'},
  workspace: {flex: 1, flexDirection: 'row', minHeight: 260},
  centerColumn: {flex: 1, minWidth: 420},
  browser: {backgroundColor: '#202326'},
  inspector: {backgroundColor: '#1b1d20'},
  panelHeader: {height: 31, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9, borderBottomWidth: 1, borderBottomColor: '#3a3d41'},
  panelTitle: {fontSize: 11, fontWeight: '700', color: '#dedfdd'},
  panelDetail: {marginLeft: 'auto', fontSize: 8, color: '#85898c'},
  tabRow: {height: 31, flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#3a3d41'},
  tab: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  tabActive: {borderBottomWidth: 2, borderBottomColor: '#b4a66a', backgroundColor: '#191b1e'},
  tabText: {fontSize: 9, color: '#c6c7c5'},
  searchRow: {height: 36, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 5, borderBottomWidth: 1, borderBottomColor: '#33363a'},
  search: {flex: 1, height: 27, paddingHorizontal: 7, fontSize: 10, color: '#efefec', borderWidth: 1, borderColor: '#44484d', backgroundColor: '#17191b'},
  iconButton: {width: 27, height: 27, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#45494d'},
  iconButtonActive: {borderColor: '#c6b975', backgroundColor: '#38372f'},
  iconText: {fontSize: 10, color: '#d4d5d3'},
  discoveryBody: {flex: 1, flexDirection: 'row'},
  sourceRail: {width: 104, paddingTop: 4, borderRightWidth: 1, borderRightColor: '#3a3d41', backgroundColor: '#181a1d'},
  railItem: {height: 23, paddingHorizontal: 8, paddingTop: 5, fontSize: 9, color: '#b9bcbd'},
  railHeading: {height: 20, paddingHorizontal: 8, paddingTop: 7, fontSize: 7, letterSpacing: 0.8, color: '#74797c'},
  results: {flex: 1},
  resultsContent: {paddingBottom: 4},
  resultsHeader: {height: 28, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 7},
  resultTitle: {fontSize: 10, fontWeight: '700', color: '#d5d6d3'},
  browserCard: {padding: 4, opacity: 0.92},
  thumbnailCard: {padding: 3},
  browserListCard: {flexDirection: 'row', alignItems: 'center'},
  browserListCopy: {flex: 1, paddingLeft: 6},
  effectSelected: {backgroundColor: '#393b3b'},
  browserThumb: {height: 52, padding: 4, justifyContent: 'space-between', borderWidth: 1, borderColor: '#3c4044'},
  thumbnailOnlyThumb: {height: 42, padding: 3},
  browserListThumb: {width: 52, height: 36},
  createGlyph: {fontSize: 25, color: '#e8dfb3'},
  effectBadge: {fontSize: 10, color: '#ffffff'},
  unavailable: {fontSize: 7, color: '#f0cfbc'},
  playBadge: {alignSelf: 'flex-end', fontSize: 9, color: '#ffffff'},
  effectName: {marginTop: 3, fontSize: 9, fontWeight: '700', color: '#ededeb'},
  effectTags: {fontSize: 7, color: '#9ca0a2'},
  emptyPanel: {padding: 14},
  emptyTitle: {fontSize: 13, color: '#e2e3e1'},
  muted: {fontSize: 9, color: '#858a8d'},
  vSplitter: {width: 8, backgroundColor: '#272a2d', borderLeftWidth: 1, borderRightWidth: 1, borderColor: '#3e4246'},
  hSplitter: {height: 8, backgroundColor: '#272a2d', borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#3e4246'},
  stage: {flex: 1, backgroundColor: '#0d0f11'},
  stageTools: {height: 31, flexDirection: 'row', alignItems: 'center', gap: 16, paddingHorizontal: 9, borderBottomWidth: 1, borderBottomColor: '#393c40'},
  stageToolText: {fontSize: 9, color: '#d4d5d3'},
  stageGpuButton: {paddingHorizontal: 7, paddingVertical: 4, borderWidth: 1, borderColor: '#716a4c'},
  stageIdentity: {marginLeft: 'auto', fontSize: 7, color: '#b7ac73'},
  stageViewport: {flex: 1, overflow: 'hidden'},
  gpuStage: {position: 'absolute', inset: 0},
  gpuStageOff: {position: 'absolute', inset: 0, alignItems: 'center', justifyContent: 'center'},
  frameGrid: {position: 'absolute', inset: 0, borderWidth: 1, borderColor: 'rgba(255,255,255,0.04)'},
  outputLabel: {position: 'absolute', top: 8, left: 10, fontSize: 7, letterSpacing: 1, color: '#bfc3c5'},
  titleBounds: {position: 'absolute', left: 10, top: 22, width: 126, height: 80, padding: 6, borderWidth: 1, borderColor: '#c3b88b'},
  stageTitle: {fontSize: 16, lineHeight: 15, fontWeight: '800', letterSpacing: 3, color: '#f1f1ee'},
  stageSubtitle: {marginTop: 6, fontSize: 5.5, letterSpacing: 0.8, color: '#c6c8c7'},
  rings: {position: 'absolute', left: 144, top: 22, width: 80, height: 80, alignItems: 'center', justifyContent: 'center'},
  ring: {position: 'absolute', borderWidth: 1, borderColor: 'rgba(235,238,232,0.42)', borderRadius: 200},
  ringLarge: {width: 76, height: 76},
  ringMedium: {width: 52, height: 52},
  ringSmall: {width: 30, height: 30},
  ringCore: {width: 14, height: 14, borderRadius: 7, backgroundColor: '#ebebe7'},
  transport: {height: 31, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, borderTopWidth: 1, borderTopColor: '#3a3d41', backgroundColor: '#1b1d20'},
  transportButton: {width: 34, fontSize: 10, color: '#dbdcda'},
  timecode: {fontSize: 9, fontWeight: '600', color: '#e4e4e1'},
  quality: {marginLeft: 'auto', fontSize: 7, color: '#84898c'},
  inspectorTitle: {paddingHorizontal: 10, paddingTop: 8, fontSize: 13, fontWeight: '700', color: '#f0f0ed'},
  parameterRow: {minHeight: 32, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: '#33363a'},
  parameterLabel: {width: 88, fontSize: 11, color: '#d5d6d3'},
  parameterValue: {flex: 1, paddingHorizontal: 7, paddingVertical: 4, fontSize: 11, fontWeight: '600', textAlign: 'right', color: '#f2f2f0', borderWidth: 1, borderColor: '#575c61'},
  stepButton: {width: 25, height: 24, alignItems: 'center', justifyContent: 'center'},
  stepText: {fontSize: 11, color: '#c8bc7b'},
  keyButton: {width: 25, height: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'transparent'},
  keyButtonAnimated: {borderColor: '#45494d'},
  keyButtonCurrent: {borderColor: '#c8bc7b', backgroundColor: '#343228'},
  keyGlyph: {fontSize: 11, color: '#b8bab8'},
  keyGlyphUnkeyed: {color: '#777c80'},
  dial: {flex: 1, height: 24, position: 'relative', overflow: 'hidden', borderWidth: 1, borderColor: '#45494d', backgroundColor: '#111315'},
  dialDragging: {borderColor: '#c8bc7b'},
  dialTicks: {position: 'absolute', left: 4, right: 44, top: 3, bottom: 3, overflow: 'hidden'},
  dialTickStrip: {position: 'absolute', left: '50%', width: 810, height: '100%', marginLeft: -405, flexDirection: 'row', alignItems: 'flex-end'},
  dialTickCell: {width: 10, height: '100%', alignItems: 'center', justifyContent: 'flex-end'},
  dialTick: {width: 1, height: 7, backgroundColor: '#686d72'},
  dialTickMajor: {height: 13, backgroundColor: '#c8bc7b'},
  dialPointer: {position: 'absolute', top: 0, bottom: 0, left: '50%', width: 1, backgroundColor: '#f0f0ed'},
  dialValue: {position: 'absolute', right: 4, top: 0, minWidth: 35, height: 22, paddingHorizontal: 2, paddingVertical: 0, fontSize: 10, textAlign: 'center', color: '#e7e7e4', backgroundColor: '#111315', zIndex: 1},
  dialValueWithUnit: {right: 13},
  dialUnit: {position: 'absolute', right: 4, top: 5, fontSize: 8, color: '#c8bc7b', zIndex: 2},
  pathOperationSection: {borderTopWidth: 1, borderColor: '#383c40', paddingVertical: 4},
  transformSection: {borderTopWidth: 1, borderColor: '#33454c', paddingVertical: 4},
  pathOperationTitle: {paddingHorizontal: 10, paddingTop: 4, fontSize: 11, fontWeight: '700', color: '#f2f2f0'},
  pathOperationDescription: {paddingHorizontal: 10, paddingTop: 2, fontSize: 11, lineHeight: 15, color: '#d5d6d3'},
  pathOperationGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 5, paddingHorizontal: 10, paddingVertical: 6},
  pathOperationButton: {borderWidth: 1, borderColor: '#45494d', paddingHorizontal: 6, paddingVertical: 5},
  pathOperationButtonText: {fontSize: 10, color: '#e7e7e4'},
  extensionBody: {flex: 1},
  extensionTabs: {flexDirection: 'row', padding: 7, gap: 5},
  extensionTab: {paddingHorizontal: 9, paddingVertical: 5, borderWidth: 1, borderColor: '#44484d'},
  timeline: {backgroundColor: '#17191b', borderTopWidth: 1, borderTopColor: '#3a3d41'},
  timelineHeader: {height: 31, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9, borderBottomWidth: 1, borderBottomColor: '#3a3d41'},
  modeText: {fontSize: 7, color: '#c6c8c7'},
  nativeTimelineBody: {flex: 1},
  nativeTimelineControls: {height: 28, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: '#3b3e41'},
  nativeTimelineTitle: {fontSize: 8, color: '#b9bcbd'},
  nativeTimelineFeedback: {marginLeft: 'auto', fontSize: 8, color: '#d8c97f'},
  nativeTimelineContent: {flex: 1, flexDirection: 'row'},
  timelineKeyTools: {width: 186, padding: 6, borderLeftWidth: 1, borderLeftColor: '#3b3e41', backgroundColor: '#17191b'},
  timelineKeyMode: {height: 23, flexDirection: 'row', gap: 2, marginHorizontal: -6, marginTop: -6, marginBottom: 6, padding: 2, borderBottomWidth: 1, borderBottomColor: '#3b3e41'},
  timelineKeyModeButton: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  timelineKeyToolsHead: {height: 22, flexDirection: 'row', alignItems: 'center'},
  timelineKeyCount: {flex: 1, fontSize: 8, color: '#d8c97f'},
  timelineKeyScope: {flexDirection: 'row', gap: 2},
  timelineKeyScopeButton: {width: 21, height: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#45494d'},
  timelineKeySections: {flexDirection: 'row', gap: 2, marginTop: 4, paddingTop: 4, borderTopWidth: 1, borderTopColor: '#3b3e41'},
  timelineKeySectionButton: {flex: 1, height: 28, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#45494d'},
  timelineKeyGlyph: {fontSize: 9, color: '#d8c97f'},
  timelineKeyActions: {flexDirection: 'row', flexWrap: 'wrap', gap: 3, marginTop: 4, paddingTop: 4, borderTopWidth: 1, borderTopColor: '#45494d'},
  timelineKeyActionTitle: {width: '100%', fontSize: 7, letterSpacing: 0.8, color: '#85898c'},
  timelineKeyActionButton: {minWidth: 36, height: 22, paddingHorizontal: 6, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#45494d'},
  timelineKeyActionButtonDisabled: {opacity: 0.45},
  timelineKeyGlyphDisabled: {color: '#85898c'},
  timelineKeyHint: {width: '100%', marginTop: 2, fontSize: 7, lineHeight: 10, color: '#85898c'},
  nativeTimelineSurface: {flex: 1},
});
