#!/usr/bin/env python3
"""INF-7e: plugin-authoring 規約準拠のスケルトンを生成する。

Usage:
  scripts/new-plugin.sh <kind> <name> [--vendor VENDOR] [--out PATH]

kind: filter | layer_source | param_driver | composite
name: lowercase ascii + underscore (例: glow)
生成 desc は validate_node_desc(INF-7c) を通る必須欄を最初から埋める。
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

KINDS = ("filter", "layer_source", "param_driver", "composite")
IDENT_RE = re.compile(r"^[a-z][a-z0-9_]*$")

# id の kind セグメント(参照実装の core.filter.* / core.param.* に合わせる)
KIND_SEG = {
    "filter": "filter",
    "layer_source": "layer_source",
    "param_driver": "param",
    "composite": "composite",
}

KIND_META = {
    "filter": {
        "trait": "FilterPlugin",
        "plugin_kind": "Filter",
        "category": "Utility",
        "min_inputs": 1,
        "max_inputs": 1,
    },
    "layer_source": {
        "trait": "LayerSourcePlugin",
        "plugin_kind": "LayerSource",
        "category": "Generate",
        "min_inputs": 0,
        "max_inputs": 0,
    },
    "param_driver": {
        "trait": "ParamDriverPlugin",
        "plugin_kind": "ParamDriver",
        "category": "Generate",
        "min_inputs": 0,
        "max_inputs": 0,
    },
    "composite": {
        "trait": "CompositePlugin",
        "plugin_kind": "Composite",
        "category": "Composite",
        "min_inputs": 2,
        "max_inputs": 8,
    },
}


def to_pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.split("_") if p)


def method_body(kind: str, plugin_id: str) -> str:
    todo = f'TODO: implement {plugin_id}'
    if kind == "filter":
        return f"""    fn render(
        &self,
        _gpu: &GpuCtx,
        _pipelines: &mut PipelineCache,
        _encoder: &mut wgpu::CommandEncoder,
        _t: RationalTime,
        _params: &ResolvedParams,
        _input: TextureRef<'_>,
        _output: TextureRef<'_>,
    ) -> Result<(), PluginError> {{
        // wgpu/WGSLのみ。パイプラインは pipelines.get_or_create_* でホストから借りる。
        // 出力は t + params + input だけで決める(純関数)。
        Err(PluginError::Render("{todo}".into()))
    }}"""
    if kind == "layer_source":
        return f"""    fn render(
        &self,
        _gpu: &GpuCtx,
        _pipelines: &mut PipelineCache,
        _encoder: &mut wgpu::CommandEncoder,
        _t: RationalTime,
        _params: &ResolvedParams,
        _ctx: LayerSourceContext,
        _output: TextureRef<'_>,
    ) -> Result<(), PluginError> {{
        Err(PluginError::Render("{todo}".into()))
    }}"""
    if kind == "param_driver":
        return f"""    fn build_track(
        &self,
        _ctx: ParamDriverContext,
        _params: &ResolvedParams,
    ) -> Result<DataTrack, PluginError> {{
        Err(PluginError::Render("{todo}".into()))
    }}"""
    if kind == "composite":
        return f"""    fn render(
        &self,
        _gpu: &GpuCtx,
        _pipelines: &mut PipelineCache,
        _encoder: &mut wgpu::CommandEncoder,
        _t: RationalTime,
        _params: &ResolvedParams,
        _inputs: &[TextureRef<'_>],
        _output: TextureRef<'_>,
    ) -> Result<(), PluginError> {{
        Err(PluginError::Render("{todo}".into()))
    }}"""
    raise ValueError(kind)


def render_source(*, kind: str, name: str, vendor: str) -> str:
    if kind not in KINDS:
        raise ValueError(f"unknown kind: {kind}")
    if not IDENT_RE.match(vendor):
        raise ValueError(f"vendor must be lowercase ascii id: {vendor}")
    if not IDENT_RE.match(name):
        raise ValueError(f"name must be lowercase ascii id: {name}")

    meta = KIND_META[kind]
    pascal = to_pascal(name)
    plugin_id = f"{vendor}.{KIND_SEG[kind]}.{name}"
    trait = meta["trait"]
    plugin_kind = meta["plugin_kind"]
    category = meta["category"]
    min_in = meta["min_inputs"]
    max_in = meta["max_inputs"]

    imports = [
        "use std::sync::OnceLock;",
        "",
        "use motolii_core::RationalTime;",
    ]
    if kind == "param_driver":
        imports.append("use motolii_eval::DataTrack;")
    imports.append("use motolii_gpu::{GpuCtx, PipelineCache};")

    plugin_imports = [
        trait,
        "NodeDesc",
        "PluginError",
        "PluginId",
        "PluginKind",
        "ResolvedParams",
        "TextureRef",
        "validate_node_desc",
    ]
    if kind == "layer_source":
        plugin_imports.append("LayerSourceContext")
    if kind == "param_driver":
        plugin_imports.append("ParamDriverContext")
    plugin_imports_sorted = ", ".join(plugin_imports)
    imports.append(f"use motolii_plugin::{{{plugin_imports_sorted}}};")

    body = method_body(kind, plugin_id)
    return f"""//! Scaffold generated by scripts/new-plugin.sh (INF-7e).
//! `motolii-plugin` に貼って肉付けする。desc は validate_node_desc 通過状態から始まる。

{chr(10).join(imports)}

pub struct {pascal};

impl {trait} for {pascal} {{
    fn desc(&self) -> &NodeDesc {{
        static DESC: OnceLock<NodeDesc> = OnceLock::new();
        DESC.get_or_init(|| NodeDesc {{
            id: PluginId("{plugin_id}"),
            version: 1,
            display_name: "{pascal}",
            category: "{category}",
            tags: &["{name}", "scaffold"],
            params: vec![],
            min_inputs: {min_in},
            max_inputs: {max_in},
        }})
    }}

{body}
}}

#[cfg(test)]
mod scaffold_tests {{
    use super::*;

    #[test]
    fn generated_desc_passes_validate_node_desc() {{
        validate_node_desc(PluginKind::{plugin_kind}, {pascal}.desc()).unwrap();
    }}
}}
"""


def scaffold_desc_fields(*, kind: str, name: str, vendor: str) -> dict:
    """テスト用: 生成 desc と同じフィールドを辞書で返す(validate と突き合わせる)。"""
    meta = KIND_META[kind]
    return {
        "id": f"{vendor}.{KIND_SEG[kind]}.{name}",
        "version": 1,
        "display_name": to_pascal(name),
        "category": meta["category"],
        "tags": [name, "scaffold"],
        "min_inputs": meta["min_inputs"],
        "max_inputs": meta["max_inputs"],
        "plugin_kind": meta["plugin_kind"],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kind", choices=KINDS)
    parser.add_argument("name", help="lowercase ascii + underscore")
    parser.add_argument("--vendor", default="core")
    parser.add_argument("--out", type=Path, help="output path (default: stdout)")
    parser.add_argument(
        "--print-desc-json",
        action="store_true",
        help="print desc fields as JSON instead of Rust (for tests)",
    )
    args = parser.parse_args(argv)

    try:
        if args.print_desc_json:
            import json

            print(json.dumps(scaffold_desc_fields(kind=args.kind, name=args.name, vendor=args.vendor)))
            return 0
        src = render_source(kind=args.kind, name=args.name, vendor=args.vendor)
    except ValueError as e:
        print(e, file=sys.stderr)
        return 1

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(src + "\n", encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(src)
        if not src.endswith("\n"):
            sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
