use crate::ui::contracts::{Binding, EaseSide, Intent, KeySpec, MenuTarget, ViewRequest};

pub(crate) fn bindings() -> [Binding; 63] {
    [
        Binding {
            key: KeySpec::Char('k'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Split,
        },
        Binding {
            key: KeySpec::Char('a'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::SelectAll,
        },
        Binding {
            key: KeySpec::ArrowLeft,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::StepFrame(-1),
        },
        Binding {
            key: KeySpec::ArrowLeft,
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::StepFrame(-10),
        },
        Binding {
            key: KeySpec::ArrowRight,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::StepFrame(1),
        },
        Binding {
            key: KeySpec::ArrowRight,
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::StepFrame(10),
        },
        Binding {
            key: KeySpec::Home,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Home,
        },
        Binding {
            key: KeySpec::End,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::End,
        },
        Binding {
            key: KeySpec::Escape,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Deselect,
        },
        Binding {
            key: KeySpec::Char(' '),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::PlayPause,
        },
        Binding {
            key: KeySpec::Delete,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::DeleteLayer,
        },
        Binding {
            key: KeySpec::Char('z'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Undo,
        },
        Binding {
            key: KeySpec::Char('z'),
            cmd: true,
            shift: true,
            alt: false,
            intent: Intent::Redo,
        },
        Binding {
            key: KeySpec::Char(']'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Reorder(1),
        },
        Binding {
            key: KeySpec::Char('['),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Reorder(-1),
        },
        Binding {
            key: KeySpec::Char('['),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::SnapEdgeToPlayhead(false),
        },
        Binding {
            key: KeySpec::Char(']'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::SnapEdgeToPlayhead(true),
        },
        Binding {
            key: KeySpec::Char('['),
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::TrimToPlayhead(false),
        },
        Binding {
            key: KeySpec::Char(']'),
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::TrimToPlayhead(true),
        },
        Binding {
            key: KeySpec::ArrowUp,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::SelectStep(-1),
        },
        Binding {
            key: KeySpec::Char('d'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Duplicate,
        },
        Binding {
            key: KeySpec::Char('g'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Group,
        },
        Binding {
            key: KeySpec::Char('g'),
            cmd: true,
            shift: true,
            alt: false,
            intent: Intent::Ungroup,
        },
        Binding {
            key: KeySpec::F9,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::EasyEase(EaseSide::Both),
        },
        Binding {
            key: KeySpec::F9,
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::EasyEase(EaseSide::In),
        },
        Binding {
            key: KeySpec::F9,
            cmd: true,
            shift: true,
            alt: false,
            intent: Intent::EasyEase(EaseSide::Out),
        },
        Binding {
            key: KeySpec::Char('u'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::ToggleKeyedOnly,
        },
        Binding {
            key: KeySpec::Char('*'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::ToggleMarker,
        },
        Binding {
            key: KeySpec::Char('*'),
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::ToggleMarker,
        },
        Binding {
            key: KeySpec::ArrowLeft,
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::JumpMarker(-1),
        },
        Binding {
            key: KeySpec::ArrowRight,
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::JumpMarker(1),
        },
        Binding {
            key: KeySpec::ArrowDown,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::SelectStep(1),
        },
        Binding {
            key: KeySpec::Char('s'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Save,
        },
        Binding {
            key: KeySpec::Enter,
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Rename,
        },
        Binding {
            key: KeySpec::Char('s'),
            cmd: true,
            shift: true,
            alt: false,
            intent: Intent::SaveAs,
        },
        Binding {
            key: KeySpec::Char('n'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::NewProject,
        },
        Binding {
            key: KeySpec::Char('o'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::OpenProject,
        },
        Binding {
            key: KeySpec::Char('='),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::View(ViewRequest::Step(1.25)),
        },
        Binding {
            key: KeySpec::Char('-'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::View(ViewRequest::Step(0.8)),
        },
        Binding {
            key: KeySpec::Char('0'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::View(ViewRequest::Fit),
        },
        Binding {
            key: KeySpec::Char('1'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::View(ViewRequest::Actual),
        },
        Binding {
            key: KeySpec::Char('q'),
            cmd: true,
            shift: false,
            alt: false,
            intent: Intent::Quit,
        },
        // AE の指: ⌘⇧D で分割(⌘K も切る)。F9 一族は macOS が食うので ⌘⌥E 一族を並べる。
        Binding {
            key: KeySpec::Char('d'),
            cmd: true,
            shift: true,
            alt: false,
            intent: Intent::Split,
        },
        Binding {
            key: KeySpec::Char('p'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Reveal(crate::doc::store::property::POSITION),
        },
        Binding {
            key: KeySpec::Char('s'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Reveal(crate::doc::store::property::SCALE),
        },
        Binding {
            key: KeySpec::Char('r'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Reveal(crate::doc::store::property::ROTATION),
        },
        Binding {
            key: KeySpec::Char('t'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Reveal(crate::doc::store::property::OPACITY),
        },
        Binding {
            key: KeySpec::Char('a'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::Reveal(crate::doc::store::property::ANCHOR),
        },
        Binding {
            key: KeySpec::Char('e'),
            cmd: true,
            shift: false,
            alt: true,
            intent: Intent::EasyEase(EaseSide::Both),
        },
        Binding {
            key: KeySpec::Char('e'),
            cmd: true,
            shift: true,
            alt: true,
            intent: Intent::EasyEase(EaseSide::In),
        },
        Binding {
            key: KeySpec::Char('e'),
            cmd: false,
            shift: true,
            alt: true,
            intent: Intent::EasyEase(EaseSide::Out),
        },
        // ⌘K は切る(NLE)。枠の設定は ⌥⌘K(AE の ⌘K は取られている)。
        Binding {
            key: KeySpec::Char('k'),
            cmd: true,
            shift: false,
            alt: true,
            intent: Intent::CompositionSettings,
        },
        Binding {
            key: KeySpec::ArrowLeft,
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::Nudge(-1.0, 0.0),
        },
        Binding {
            key: KeySpec::ArrowRight,
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::Nudge(1.0, 0.0),
        },
        Binding {
            key: KeySpec::ArrowUp,
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::Nudge(0.0, -1.0),
        },
        Binding {
            key: KeySpec::ArrowDown,
            cmd: false,
            shift: false,
            alt: true,
            intent: Intent::Nudge(0.0, 1.0),
        },
        Binding {
            key: KeySpec::ArrowLeft,
            cmd: false,
            shift: true,
            alt: true,
            intent: Intent::Nudge(-10.0, 0.0),
        },
        Binding {
            key: KeySpec::ArrowRight,
            cmd: false,
            shift: true,
            alt: true,
            intent: Intent::Nudge(10.0, 0.0),
        },
        Binding {
            key: KeySpec::ArrowUp,
            cmd: false,
            shift: true,
            alt: true,
            intent: Intent::Nudge(0.0, -10.0),
        },
        Binding {
            key: KeySpec::ArrowDown,
            cmd: false,
            shift: true,
            alt: true,
            intent: Intent::Nudge(0.0, 10.0),
        },
        Binding {
            key: KeySpec::ArrowUp,
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::SelectExtend(-1),
        },
        Binding {
            key: KeySpec::ArrowDown,
            cmd: false,
            shift: true,
            alt: false,
            intent: Intent::SelectExtend(1),
        },
        // マーカーは NLE の M でも打てる(AE のテンキー `*` と並べる)。
        Binding {
            key: KeySpec::Char('m'),
            cmd: false,
            shift: false,
            alt: false,
            intent: Intent::ToggleMarker,
        },
    ]
}

pub(crate) fn entries(target: MenuTarget) -> Vec<(&'static str, Intent)> {
    let mut rows = Vec::new();
    if matches!(target, MenuTarget::Layer(_)) {
        rows.extend([
            ("Split at Playhead", Intent::Split),
            ("Duplicate", Intent::Duplicate),
            ("Rename", Intent::Rename),
            ("Delete", Intent::DeleteLayer),
        ]);
    } else {
        rows.extend([
            ("Play / Pause", Intent::PlayPause),
            ("Go to Start", Intent::Home),
            ("Go to End", Intent::End),
        ]);
    }
    rows.extend([
        ("Select All", Intent::SelectAll),
        ("Deselect", Intent::Deselect),
        ("Undo", Intent::Undo),
        ("Redo", Intent::Redo),
    ]);
    rows
}
