# CAPABILITY: material = MaterialX + OpenPBR. Asks MaterialX's own MSL generator for the blue-glass surface shader.
# run with Blender's bundled python (MaterialX 1.39.2). Writes glass.vert.metal / glass.frag.metal next to this file.
import os, sys
import MaterialX as mx
import MaterialX.PyMaterialXGenShader as gs
import MaterialX.PyMaterialXGenGlsl as _glsl  # load order matters for the bundled dylibs
import MaterialX.PyMaterialXGenMsl as msl

here = os.path.dirname(os.path.abspath(__file__))
doc = mx.createDocument()
stdlib = mx.createDocument()
mx.loadLibraries(mx.getDefaultDataLibraryFolders(), mx.getDefaultDataSearchPath(), stdlib)
doc.importLibrary(stdlib)
s = doc.addNode("open_pbr_surface", "glass", "surfaceshader")
for name, typ, val in [("base_weight", "float", 0.0), ("transmission_weight", "float", 1.0),
                       ("transmission_color", "color3", mx.Color3(0.06, 0.30, 1.0)), ("transmission_depth", "float", 0.0),
                       ("specular_ior", "float", 1.5), ("specular_roughness", "float", 0.02)]:
    s.setInputValue(name, val, typ)
m = doc.addMaterialNode("glass_mat", s)
gen = msl.MslShaderGenerator.create()
ctx = gs.GenContext(gen)
ctx.registerSourceCodeSearchPath(mx.getDefaultDataSearchPath())
shader = gen.generate("glass", m, ctx)
for stage, ext in [(gs.VERTEX_STAGE, "vert"), (gs.PIXEL_STAGE, "frag")]:
    open(os.path.join(here, f"glass.{ext}.metal"), "w").write(shader.getSourceCode(stage))
print("ok", [len(shader.getSourceCode(x)) for x in (gs.VERTEX_STAGE, gs.PIXEL_STAGE)])

# The uniform blocks, exactly as MaterialX declared them, for the host to fill (layout + MaterialX's own default values).
import re
frag = shader.getSourceCode(gs.PIXEL_STAGE)
vert = shader.getSourceCode(gs.VERTEX_STAGE)
def block(src, name):
    return re.search(r"struct %s\s*\{.*?\};" % name, src, re.S).group(0)
out = ["// generated by gen_glass.py from MaterialX's shader interface. Do not edit.", "#pragma once", "#include <simd/simd.h>", "#include <string.h>",
       "namespace mtlx {", "typedef simd_float2 vec2; typedef simd_float3 vec3; typedef simd_float4 vec4; typedef simd_float3 float3; typedef simd_float4x4 mat4;",
       "struct surfaceshader { float3 color; float3 transparency; };", "struct displacementshader { float3 offset; float scale; };",
       "#define MAX_LIGHT_SOURCES 3", block(frag, "LightData"), block(frag, "LightData_pixel"), block(frag, "PublicUniforms"),
       block(frag, "PrivateUniforms").replace("PrivateUniforms", "PrivateUniformsFrag"), block(vert, "PrivateUniforms").replace("PrivateUniforms", "PrivateUniformsVert"),
       "static inline void glass_defaults(PublicUniforms& u) {", "    memset(&u, 0, sizeof(u));"]
pub = shader.getStage(gs.PIXEL_STAGE).getUniformBlock("PublicUniforms")
for i in range(pub.size()):
    p = pub[i]
    v, t = p.getValue(), p.getType().getName()
    if v is None: continue
    s = v.getValueString()
    if t == "float": out.append(f"    u.{p.getVariable()} = {float(s)}f;")
    elif t in ("integer",): out.append(f"    u.{p.getVariable()} = {int(s)};")
    elif t == "boolean": out.append(f"    u.{p.getVariable()} = {s.lower()};")
    elif t in ("color3", "vector3"): out.append(f"    u.{p.getVariable()} = simd_make_float3({', '.join(str(float(x)) + 'f' for x in s.split(','))});")
out += ["}", "}"]
open(os.path.join(here, "glass_uniforms.h"), "w").write("\n".join(out) + "\n")
