// generated by gen_glass.py from MaterialX's shader interface. Do not edit.
#pragma once
#include <simd/simd.h>
#include <string.h>
namespace mtlx {
typedef simd_float2 vec2; typedef simd_float3 vec3; typedef simd_float4 vec4; typedef simd_float3 float3; typedef simd_float4x4 mat4;
struct surfaceshader { float3 color; float3 transparency; };
struct displacementshader { float3 offset; float scale; };
#define MAX_LIGHT_SOURCES 3
struct LightData
{
    int type;
    float pad0;
    float pad1;
    float pad2;
};
struct LightData_pixel
{
    LightData u_lightData[MAX_LIGHT_SOURCES];
};
struct PublicUniforms
{
    surfaceshader backsurfaceshader;
    displacementshader displacementshader1;
    float glass_base_weight;
    vec3 glass_base_color;
    float glass_base_diffuse_roughness;
    float glass_base_metalness;
    float glass_specular_weight;
    vec3 glass_specular_color;
    float glass_specular_roughness;
    float glass_specular_ior;
    float glass_specular_roughness_anisotropy;
    float glass_transmission_weight;
    vec3 glass_transmission_color;
    float glass_transmission_depth;
    vec3 glass_transmission_scatter;
    float glass_transmission_scatter_anisotropy;
    float glass_transmission_dispersion_scale;
    float glass_transmission_dispersion_abbe_number;
    float glass_subsurface_weight;
    vec3 glass_subsurface_color;
    float glass_subsurface_radius;
    vec3 glass_subsurface_radius_scale;
    float glass_subsurface_scatter_anisotropy;
    float glass_fuzz_weight;
    vec3 glass_fuzz_color;
    float glass_fuzz_roughness;
    float glass_coat_weight;
    vec3 glass_coat_color;
    float glass_coat_roughness;
    float glass_coat_roughness_anisotropy;
    float glass_coat_ior;
    float glass_coat_darkening;
    float glass_thin_film_weight;
    float glass_thin_film_thickness;
    float glass_thin_film_ior;
    float glass_emission_luminance;
    vec3 glass_emission_color;
    float glass_geometry_opacity;
    bool glass_geometry_thin_walled;
};
struct PrivateUniformsFrag
{
    mat4 u_envMatrix;
    float u_envLightIntensity;
    int u_envRadianceMips;
    int u_envRadianceSamples;
    bool u_refractionTwoSided;
    vec3 u_viewPosition;
    int u_numActiveLightSources;
};
struct PrivateUniformsVert
{
    mat4 u_worldMatrix;
    mat4 u_viewProjectionMatrix;
    mat4 u_worldInverseTransposeMatrix;
};
static inline void glass_defaults(PublicUniforms& u) {
    memset(&u, 0, sizeof(u));
    u.glass_base_weight = 0.0f;
    u.glass_base_color = simd_make_float3(0.8f, 0.8f, 0.8f);
    u.glass_base_diffuse_roughness = 0.0f;
    u.glass_base_metalness = 0.0f;
    u.glass_specular_weight = 1.0f;
    u.glass_specular_color = simd_make_float3(1.0f, 1.0f, 1.0f);
    u.glass_specular_roughness = 0.02f;
    u.glass_specular_ior = 1.5f;
    u.glass_specular_roughness_anisotropy = 0.0f;
    u.glass_transmission_weight = 1.0f;
    u.glass_transmission_color = simd_make_float3(0.06f, 0.3f, 1.0f);
    u.glass_transmission_depth = 0.0f;
    u.glass_transmission_scatter = simd_make_float3(0.0f, 0.0f, 0.0f);
    u.glass_transmission_scatter_anisotropy = 0.0f;
    u.glass_transmission_dispersion_scale = 0.0f;
    u.glass_transmission_dispersion_abbe_number = 20.0f;
    u.glass_subsurface_weight = 0.0f;
    u.glass_subsurface_color = simd_make_float3(0.8f, 0.8f, 0.8f);
    u.glass_subsurface_radius = 1.0f;
    u.glass_subsurface_radius_scale = simd_make_float3(1.0f, 0.5f, 0.25f);
    u.glass_subsurface_scatter_anisotropy = 0.0f;
    u.glass_fuzz_weight = 0.0f;
    u.glass_fuzz_color = simd_make_float3(1.0f, 1.0f, 1.0f);
    u.glass_fuzz_roughness = 0.5f;
    u.glass_coat_weight = 0.0f;
    u.glass_coat_color = simd_make_float3(1.0f, 1.0f, 1.0f);
    u.glass_coat_roughness = 0.0f;
    u.glass_coat_roughness_anisotropy = 0.0f;
    u.glass_coat_ior = 1.6f;
    u.glass_coat_darkening = 1.0f;
    u.glass_thin_film_weight = 0.0f;
    u.glass_thin_film_thickness = 0.5f;
    u.glass_thin_film_ior = 1.4f;
    u.glass_emission_luminance = 0.0f;
    u.glass_emission_color = simd_make_float3(1.0f, 1.0f, 1.0f);
    u.glass_geometry_opacity = 1.0f;
    u.glass_geometry_thin_walled = false;
}
}
